#!/usr/bin/env bash

## Author  : Aditya Shakya
## Twitter : @adi1090x
## Github  : @adi1090x
## Reddit  : @adi1090x

## A simple script to change color-schemes & fonts of kitty terminal.

## ANSI Colors (FG & BG)
RED="$(printf '\033[31m')"  GREEN="$(printf '\033[32m')"  ORANGE="$(printf '\033[33m')"  BLUE="$(printf '\033[34m')"
MAGENTA="$(printf '\033[35m')"  CYAN="$(printf '\033[36m')"  WHITE="$(printf '\033[37m')" BLACK="$(printf '\033[30m')"
REDBG="$(printf '\033[41m')"  GREENBG="$(printf '\033[42m')"  ORANGEBG="$(printf '\033[43m')"  BLUEBG="$(printf '\033[44m')"
MAGENTABG="$(printf '\033[45m')"  CYANBG="$(printf '\033[46m')"  WHITEBG="$(printf '\033[47m')" BLACKBG="$(printf '\033[40m')"
DEFAULT_FG="$(printf '\033[39m')"  DEFAULT_BG="$(printf '\033[49m')"

## Directories
KITTY_DIR="$HOME/.config/kitty"
COLORS_DIR='/usr/share/kitty-cat/colors'
FONTS_DIR='/usr/share/fonts/kitty-cat'

## Banner
banner () {
    clear
    echo "
    ${BLUE}/\___/\ 			          
    ${BLUE}\ -.- / ${RED} ┃ ┃┛━┏┛━┏┛┃ ┃ ${GREEN} ┏━┛┏━┃━┏┛  
    ${BLUE}'-.^.-' ${RED} ┏┛ ┃ ┃  ┃ ━┏┛ ${GREEN} ┃  ┏━┃ ┃   
    ${BLUE}  /'\   ${RED} ┛ ┛┛ ┛  ┛  ┛  ${GREEN} ━━┛┛ ┛ ┛   

    ${BLUE}[${RED}*${BLUE}] ${ORANGE}By- Aditya Shakya ${RED}//${ORANGE} adi1090x"
}

## Script Termination
exit_on_signal_SIGINT () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script interrupted." 2>&1; echo; reset_color; }
    exit 0
}

exit_on_signal_SIGTERM () {
    { printf "\n\n%s\n" "    ${BLUE}[${RED}*${BLUE}] ${RED}Script terminated." 2>&1; echo; reset_color; }
    exit 0
}

trap exit_on_signal_SIGINT SIGINT
trap exit_on_signal_SIGTERM SIGTERM

## Reset terminal colors
reset_color() {
	tput sgr0   # reset attributes
	tput op     # reset color
    return
}

## Available color-schemes & fonts
check_files () {
    if [[ "$1" = colors ]]; then
        colors=($(ls $COLORS_DIR))
        echo ${#colors[@]}
    elif [[ "$1" = fonts ]]; then
        fonts=($(ls $FONTS_DIR))
        echo ${#fonts[@]}
    fi
    return
}

total_colors=$(check_files colors)
total_fonts=$(check_files fonts)

## Reload Settings
reload_settings () {
    echo "    ${BLUE}[${RED}*${BLUE}] ${MAGENTA}Reloading Settings..."
    kitty @ set-colors --all $KITTY_DIR/colors.conf > /dev/null
    { echo "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Applied Successfully."; echo; }
    return
}

## Apply color-schemes
apply_colors () {
    local count=1

    # List the color-schemes
    color_schemes=($(ls $COLORS_DIR))
    for colors in "${color_schemes[@]}"; do
        colors_name=$(echo $colors)
        echo ${ORANGE}"    [$count] ${colors_name%.*}"
        count=$(($count+1))
    done

    # Read user selection
    { echo; read -p ${BLUE}"    [${RED}Select Color Scheme (1 to $total_colors)${BLUE}]: ${GREEN}" answer; echo; }

    # Apply color-scheme
    if [[ (-n "$answer") && ("$answer" -le $total_colors) ]]; then
        scheme=${color_schemes[(( answer - 1 ))]}
        echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Applying Color Scheme..."
        cat $COLORS_DIR/$scheme > $KITTY_DIR/colors.conf
        { reload_settings; reset_color; exit; }
    else
        echo -n "    ${BLUE}[${RED}!${BLUE}] ${RED}Invalid Option, Try Again."
        { sleep 2; banner; echo; apply_colors; }
    fi
    return
}

## Apply fonts
apply_fonts () {
    local count=1

    # List fonts
    fonts_list=($(ls $FONTS_DIR))
    for fonts in "${fonts_list[@]}"; do
        fonts_name=$(echo $fonts)
        echo ${ORANGE}"    [$count] ${fonts_name%.*}"
        count=$(($count+1))
    done

    # Read user selection
    { echo; read -p ${BLUE}"    [${RED}Select font (1 to $total_fonts)${BLUE}]: ${GREEN}" answer; echo; }

    # Apply fonts
    if [[ (-n "$answer") && ("$answer" -le $total_fonts) ]]; then
        font_ttf=${fonts_list[(( answer - 1 ))]}
        actual_font_name=$(fc-list | grep -i $font_ttf | head -n 1 | cut -d':' -f2)
        { read -p ${BLUE}"    [${RED}Enter Font Size (Default is 10)${BLUE}]: ${GREEN}" font_size; echo; }
        echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Applying Fonts..."
        sed -i -e "s/font_family .*/font_family      $actual_font_name/g" $KITTY_DIR/kitty.conf
        sed -i -e "s/font_size .*/font_size  ${font_size:-10}/g" $KITTY_DIR/kitty.conf
        { echo "    ${BLUE}[${RED}!${BLUE}] ${ORANGE}Please Restart Kitty."; echo; }
        { reset_color; exit; }
    else
        echo -n "    ${BLUE}[${RED}!${BLUE}] ${RED}Invalid Option, Try Again."
        { sleep 2; banner; echo; apply_fonts; }
    fi
    return
}

## Random style
random_style () {
    echo "    ${BLUE}[${RED}*${BLUE}] ${ORANGE}Setting Random Style..."
    random_scheme=$(ls $COLORS_DIR | shuf -n 1)
    { cat $COLORS_DIR/$random_scheme > $KITTY_DIR/colors.conf; }
    { reload_settings; reset_color; exit; }
}

## Import files
import_files () {
    echo "    ${BLUE}[${RED}L${BLUE}] ${ORANGE}Local File (Enter path to file)
    ${BLUE}[${RED}I${BLUE}] ${ORANGE}Internet File (Enter File URL)"
    { echo; read -p ${BLUE}"    [${RED}Select Option${BLUE}]: ${GREEN}" option; echo; }

    temp_file=$(mktemp /tmp/kitty_XXXXXXXXXX.conf)

    if [[ "$option" =~ ^[l/L/i/I]$ ]]; then
        if [[ "$option" =~ ^[l/L]$ ]]; then
            { read -p ${BLUE}"    [${RED}Enter Path To Color-scheme${BLUE}]: ${GREEN}" file_path; echo; }
            cat $file_path > $KITTY_DIR/colors.conf
            { reload_settings; reset_color; exit; }
        elif [[ "$option" =~ ^[i/I]$ ]]; then
            { read -p ${BLUE}"    [${RED}Enter Color-scheme URL${BLUE}]: ${GREEN}" file_link; echo; }
            wget -o /tmp/log -O $temp_file $file_link
            cat $temp_file > $KITTY_DIR/colors.conf
            { reload_settings; reset_color; exit; }
        fi
    else
        echo -n "    ${BLUE}[${RED}!${BLUE}] ${RED}Invalid Option, Try Again."
        { sleep 2; banner; echo; import_files; }
    fi
}

## About program
about_program () {
    echo -n ${BLUE}"    ┌───────────────────────────────────────────────────────────────┐
    │  			     ┏━┓┏┓ ┏━┓╻ ╻╺┳╸			    │
    │  			     ┣━┫┣┻┓┃ ┃┃ ┃ ┃ 			    │
    │  			     ╹ ╹┗━┛┗━┛┗━┛ ╹ 			    │
    │───────────────────────────────────────────────────────────────│
    │                                                               │
    │ >>  'kitty-cat' is a simple program that provides color 	    │
    │     schemes and powerline-ready fonts to customize the        │
    │     appearance of the kitty terminal.                         │
    │                                                               │
    │                                                               │
    │ >>  Author   :  Aditya Shakya                                 │
    │     Twitter  :  https://twitter.com/adi1090x                  │
    │     Github   :  https://github.com/adi1090x                   │
    │     Reddit   :  https://www.reddit.com/user/adi1090x          │
    │                                                               │
    └───────────────────────────────────────────────────────────────┘"
    { echo; read -p "    ${BLUE}[${RED}*${BLUE}] ${GREEN}Press ${GREENBG}${BLACK} Enter ${DEFAULT_BG}${GREEN} To Return To Main Menu."; }
}

## Main menu
until [[ "$REPLY" =~ ^[q/Q]$ ]]; do
    banner
    echo "
    ${BLUE}[${RED}C${BLUE}] ${GREEN}Colors ($total_colors)
    ${BLUE}[${RED}F${BLUE}] ${GREEN}Fonts ($total_fonts)
    ${BLUE}[${RED}R${BLUE}] ${GREEN}Random
    ${BLUE}[${RED}I${BLUE}] ${GREEN}Import
    ${BLUE}[${RED}A${BLUE}] ${GREEN}About
    ${BLUE}[${RED}Q${BLUE}] ${GREEN}Quit
    "

    { read -p ${BLUE}"    [${RED}Select Option${BLUE}]: ${GREEN}"; echo; }

    if [[ "$REPLY" =~ ^[c/C/f/F/r/R/i/I/a/A/q/Q]$ ]]; then      #validate input
        if [[ "$REPLY" =~ ^[c/C]$ ]]; then
            apply_colors
        elif [[ "$REPLY" =~ ^[f/F]$ ]]; then
            apply_fonts
        elif [[ "$REPLY" =~ ^[r/R]$ ]]; then
            random_style
        elif [[ "$REPLY" =~ ^[i/I]$ ]]; then
            import_files
        elif [[ "$REPLY" =~ ^[a/A]$ ]]; then
            about_program
        fi
    else
        echo -n "    ${BLUE}[${RED}!${BLUE}] ${RED}Invalid Option, Try Again."
        sleep 2
    fi
done
{ echo "    ${BLUE}[${RED}*${BLUE}] ${RED}Bye Bye, Have A Nice Day!"; echo; reset_color; exit 0; }